# Generated by Django 4.2.3 on 2023-08-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_date", models.DateField()),
                ("father_name", models.CharField(max_length=100)),
                ("id_number", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("mother_name", models.CharField(max_length=100)),
                ("mobile_number", models.CharField(max_length=20)),
                ("did_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "husband_or_wife_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("address", models.TextField()),
                ("religion", models.CharField(max_length=50)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "second_contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="employee_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Granter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("father_name", models.CharField(max_length=100)),
                ("mobile_number", models.CharField(max_length=20)),
                ("address", models.TextField()),
                (
                    "husband_or_wife_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("shop", models.CharField(blank=True, max_length=200, null=True)),
                ("religion", models.CharField(max_length=50)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "second_contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "language",
                    models.CharField(
                        choices=[("Bangla", "Bangla"), ("English", "English")],
                        max_length=10,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("member", "Member"), ("employee", "Employee")],
                        max_length=10,
                    ),
                ),
                (
                    "login_permission",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.employee",
                    ),
                ),
            ],
        ),
    ]
