# Generated by Django 4.2.4 on 2023-08-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_login_employeelogin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('item_model', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
