# Generated by Django 4.2.4 on 2023-08-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hotel_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
